// Code generated by goctl. DO NOT EDIT.
package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Course struct {
	ID           string `json:"id"`
	Title        string `json:"title"`
	RoutePath    string `json:"route_path"`
	Description  string `json:"description"`
	CoverImg     string `json:"cover_img"`
	TotalScore   int64  `json:"total_score"`
	UserCnt      int64  `json:"user_cnt"`
	StartStatus  int    `json:"start_status"`
	ShareURL     string `json:"share_url"`
	ExtendedInfo string `json:"extended_info"`
}

type CourseList struct {
	List []Course `json:"list"`
}

type CourseListResp struct {
	Base
	Data CourseList `json:"data"`
}

type GetUserCourseLessonReq struct {
	CourseId string `path:"course_id"`
	LessonId string `path:"lesson_id"`
}
