// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	courses "github.com/WTFAcademy/platform/internal/handler/courses"
	"github.com/WTFAcademy/platform/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/courses",
				Handler: courses.AllCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/:course_id",
				Handler: courses.GetCourseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/:course_id/lesson",
				Handler: courses.GetCourseQuizListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/:course_id/user_lessons/:lesson_id",
				Handler: courses.GetUserCourseLessonHandler(serverCtx),
			},
		},
	)
}
